import { StyleSheet } from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
export const Colors = {
  // mainColor: '#00BF63',
  mainColor: '#BD2BAF',
  background: '#ffffff',
  buttoncolor: '#4686D4',
  lightbutton: '#CADCCE',
  black: '#000000',
  lightblack: '#475569',
  inputColor: '#f3f9ff',
  white: '#FFFFFF',
  red: '#FF4B26',
  green: '#00AA38',
  lightgreen: '#ECF7F3',
  lightgrey: '#D2E0FF',
  boardingColor: '#F1F1F1',
  lightblue: '#0052B4',
  placeholder: '#C9C9C9',
  darkblue: '#101835',
  lightblue: '#6074BC',
  grey: '#E3E3E7',
  lightgrey: '#7D7F88',
};

const fonts = {
  bold: 'Helvetica-Bold',
  medium: 'Helvetica',
  light: 'helvetica-light',
};

const images = {
  onboardpic1: require('../Assets/Onboardback1.png'),
  Logo: require('../Assets/logo.png'),
  avatarpic: require('../Assets/avatarpic.png'),
  tickcong: require('../Assets/tickcong.png'),
  finaltick: require('../Assets/finaltick.png'),
  homepic: require('../Assets/homepic.png'),
  mainImage: require('../Assets/Background.png'),
  taskspic: require('../Assets/taskspic.png'),
  chatpic: require('../Assets/chatpic.png'),
  profilepic: require('../Assets/profilepic.png'),
  menuIcon: require('../Assets/menuIcon.png'),
  avatarhome: require('../Assets/avatarhome.png'),
  useraddIcon: require('../Assets/useraddIcon.png'),
  aiIcon: require('../Assets/aiIcon.png'),
  tabIcon: require('../Assets/tabIcon.png'),
  calendarIcon: require('../Assets/calendarIcon.png'),
  clockIcon: require('../Assets/clockIcon.png'),
  inviteuser: require('../Assets/inviteuser.png'),
  mainbackground: require('../Assets/mainbackground.png'),
  Homebackground: require('../Assets/Homebackground.png'),
  myallbackbg: require('../Assets/myallbackbg.png'),

  lighting: require('../Assets/lighting.png'),
  dummypic1: require('../Assets/dummypic1.png'),
  dummypic2: require('../Assets/dummypic2.png'),
  dummypic3: require('../Assets/dummypic3.png'),
  flag: require('../Assets/flag.png'),
  sendIcon: require('../Assets/sendIcon.png'),
  uploadIcon: require('../Assets/WhiteUpload.png'),
  // uploadIcon: require('../Assets/uploadIcon.png'),
  mySplash: require('../Assets/mySplash.png'),
  mySplash2: require('../Assets/mySplash2.png'),
  mySplash3: require('../Assets/mySplash3.png'),
  myalarmbg: require('../Assets/myalarmbg.gif'),

  taskpic1: require('../Assets/taskpic1.png'),
  taskpic2: require('../Assets/taskpic2.png'),
  taskpic3: require('../Assets/taskpic3.png'),
  addtaskIcon: require('../Assets/addtaskIcon.png'),
  addreminderIcon: require('../Assets/addreminderIcon.png'),
  tracktimeIcon: require('../Assets/tracktimeIcon.png'),
  documentIcon: require('../Assets/documentIcon.png'),
  noteIcon: require('../Assets/noteIcon.png'),
  plusIcon: require('../Assets/plusIcon.png'),
  attach: require('../Assets/attach.png'),
  dummyuserpic: require('../Assets/dummyuserpic.png'),

  feedbackImg: require('../Assets/feedbackImg.png'),
  starImg: require('../Assets/starImg.png'),
  applogoImg: require('../Assets/applogoImg.png'),
  drawerImg: require('../Assets/drawerImg.png'),
  drawerImg2: require('../Assets/drawerImg2.png'),
  Applogo2: require('../Assets/logo.png'),

  notificationIcon: require('../Assets/notificationIcon.png'),
  alarmImg: require('../Assets/alarmImg.png'),
  alarmImgoff: require('../Assets/alarmImg.png'),

  plusButton: require('../Assets/plusButton.png'),
  alarmbg: require('../Assets/alarmbg.png'),
  whiteLogo: require('../Assets/whiteLogo.png'),
  alarmsetImg: require('../Assets/alarmsetImg.png'),
  statsIcon: require('../Assets/statsIcon.png'),
  statuspic1: require('../Assets/statuspic1.png'),
  statuspic2: require('../Assets/statuspic2.png'),
  statuspic3: require('../Assets/statuspic3.png'),
  statuspic4: require('../Assets/statuspic4.png'),
  picmeeting4: require('../Assets/picmeeting4.png'),
  picmeeting5: require('../Assets/picmeeting5.png'),
  nodata: require('../Assets/nodata.png'),

  onboard1: require('../Assets/onboard1.png'),
  onboard2: require('../Assets/onboard2.png'),
  onboard3: require('../Assets/onboard3.png'),
  onboard4: require('../Assets/onboard4.png'),
  onboard5: require('../Assets/onboard5.png'),
  onboard6: require('../Assets/onboard6.png'),
  onboard7: require('../Assets/onboard7.png'),
  modalLogo: require('../Assets/modalLogo.png'),
  google: require('../Assets/google.png'),
  mynotiIcon: require('../Assets/mynotiIcon.png'),

  communityback1: require('../Assets/communityback1.png'),
  communityback2: require('../Assets/communityback2.png'),

  communitybackground: require('../Assets/communitybackground.png'),
  communitybackground2: require('../Assets/communitybackground2.png'),

  heartIcon: require('../Assets/heartIcon.png'),
  messageIcon: require('../Assets/messageIcon.png'),
  shareIcon: require('../Assets/shareIcon.png'),
  shareImg: require('../Assets/shareImg.png'),
  reportImg: require('../Assets/reportImg.png'),
  cameraIcon: require('../Assets/cameraIcon.png'),
  aibackground: require('../Assets/aibackground.png'),
  aiLogo: require('../Assets/aiLogo.png'),
  subbackground: require('../Assets/subbackground.png'),
  // launch_screen: require('../Assets/launch_screen.png'),
  launch_screen: require('../Assets/lunchScreen.png'),

  joincommunityImg: require('../Assets/joincommunityImg.png'),
  menuIcon2: require('../Assets/menuIcon2.png'),
  podcastback1: require('../Assets/podcastback1.png'),
  podcastIcon: require('../Assets/podcastIcon.png'),
  podcastpic1: require('../Assets/podcastpic1.png'),
  podcastpic2: require('../Assets/podcastpic2.png'),
  podcastpic3: require('../Assets/podcastpic3.png'),
  podcastpic4: require('../Assets/podcastpic4.png'),
  editprofile: require('../Assets/editprofile.png'),
  recordingpic: require('../Assets/racordingpic.png'),

  InprogressImg: require('../Assets/InprogressImg.png'),
  PendingImg: require('../Assets/PendingImg.png'),
  subscribedImg: require('../Assets/subscribedImg.jpg'),

  jnlonboard1: require('../Assets/jnlonboard1.png'),
  jnlonboard2: require('../Assets/jnlonboard2.png'),
  jnlonboard3: require('../Assets/jnlonboard3.png'),
  jnlonboard4: require('../Assets/jnlonboard4.png'),
  jnlonboard5: require('../Assets/jnlonboard5.png'),
  jnlonboard6: require('../Assets/jnlonboard6.png'),
  jnlonboard7: require('../Assets/jnlonboard7.png'),

  sad: require('../Assets/sad.png'),
  happy: require('../Assets/happy.png'),

  completeT: require('../Assets/completeT.png'),
};
export { fonts, images };

export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    //   padding: 20,

    backgroundColor: Colors.white,
  },
  checkrow: {
    flexDirection: 'row',
    alignItems: 'center',
    // marginHorizontal: wp(5),
    marginTop: wp(3),
    justifyContent: 'space-between',
  },
  btnView: {
    width: wp(88),
    height: wp(13),
    borderRadius: 12,
    backgroundColor: Colors.mainColor,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    // elevation: 2,
  },
  titleText: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: Colors.white,
  },
  cell: {
    width: wp(14),
    height: hp(7),
    lineHeight: wp(14),
    fontSize: 20,
    fontFamily: fonts.medium,
    borderRadius: wp(4),
    backgroundColor: '#00000066',
    textAlign: 'center',
    marginHorizontal: wp(4),
    color: Colors.white,
    elevation: 2,
    // borderWidth: 0.5,
    borderColor: Colors.mainColor,
  },
  flatView: {
    width: wp(89),
    borderRadius: wp(2),
    backgroundColor: Colors.white,
    marginBottom: wp(2),
    elevation: 2,
    paddingHorizontal: wp(3),
    paddingVertical: wp(3),
    alignSelf: 'center',
    marginTop: wp(1),
    shadowOffset: { height: 2, width: 4 },
    shadowOpacity: 0.2,
    shadowColor: '#4686D4',
    shadowRadius: 8,
  },
  uploadpicView: {
    width: wp(90),
    height: 160,
    // borderWidth: 1,
    borderColor: '#667085',
    borderStyle: 'dotted',
    borderRadius: wp(3),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#00000099',
  },
  descText: {
    fontSize: 12,
    fontFamily: fonts.medium,
    color: Colors.lightblack,
  },
  tasksView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: wp(5),
    paddingHorizontal: wp(2),
    paddingVertical: wp(2),
    backgroundColor: Colors.lightgreen,
    borderRadius: wp(2),
    elevation: 1,
  },
  mainText: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: Colors.white,
  },
  modalContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    width: '80%',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 20,
  },
  headerText: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  closeText: {
    fontSize: 20,
  },
  grid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  column: {
    alignItems: 'center',
  },
  item: {
    padding: 10,
    margin: 5,
    // borderWidth: 1,
    // borderColor: '#ccc',
    borderRadius: 5,
  },
  selectedItem: {
    backgroundColor: '#2E7D32',
  },
  itemText: {
    fontSize: 16,
  },
  selectedTime: {
    fontSize: 20,
    color: '#2E7D32',
    marginBottom: 20,
  },
  selectButton: {
    backgroundColor: '#2E7D32',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
  },
  selectButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    width: '85%',
    maxHeight: '70%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
  },
  pickerWrapper: {
    marginBottom: 20,
    flexDirection: 'row',
  },
  pickerContainer: {
    // marginBottom: 20,
    alignItems: 'center',
  },
  pickerLabel: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
    color: '#333',
  },
  pickerScroll: {
    flexDirection: 'row',
    paddingHorizontal: 20,
  },
  pickerItem: {
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 5,
    borderRadius: 8,
  },
  selectedPickerItem: {
    backgroundColor: Colors.mainColor,
  },
  pickerText: {
    fontSize: 18,
    color: '#666',
  },
  selectedPickerText: {
    color: 'white',
    fontWeight: 'bold',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  button: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  cancelButton: {
    backgroundColor: '#f0f0f0',
  },
  confirmButton: {
    backgroundColor: Colors.mainColor,
  },
  cancelButtonText: {
    color: '#333',
    fontSize: 16,
    fontWeight: '600',
  },
  confirmButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  questionStyle: {
    fontSize: 12,
    fontFamily: fonts.medium,
    color: '#616161',
    marginTop: wp(2),
  },
  accountView: {
    marginTop: wp(10),
    paddingHorizontal: wp(4),
    alignSelf: 'center',
    width: wp(90),
    height: wp(13),
    backgroundColor: '#BD2BAF33',
    borderRadius: wp(2),
    // elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },

  messageList: {
    flex: 1,
  },
  botMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#e0e0e0',
    padding: 10,
    margin: 10,
    borderRadius: 10,
    maxWidth: '70%',
  },
  userMessage: {
    alignSelf: 'flex-start',
    backgroundColor: '#6200ea',
    padding: 10,
    margin: 10,
    borderRadius: 10,
    maxWidth: '70%',
    // marginBottom:wp(20)
  },
  messageText: {
    fontSize: 14,
    color: '#000',
  },
  messagebotText: {
    fontSize: 14,
    color: 'white',
  },
  questionContainer: {
    padding: 10,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#ddd',
    // marginBottom:wp(20),
    position: 'absolute',
    bottom: wp(13),
  },
  questionList: {
    maxHeight: 210,
  },
  questionButton: {
    backgroundColor: '#6200ea',
    padding: 10,
    marginVertical: 5,
    borderRadius: 5,
  },
  questionText: {
    color: '#fff',
    fontSize: 12,
  },
  loadingContainer: {
    padding: 10,
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 14,
    color: '#6200ea',
  },
  addplanningView: {
    width: wp(90),
    height: wp(13),
    // backgroundColor:Colors.lightgreen,
    // borderTopWidth:1,
    // borderTopColor:'#E9F1FF',
    borderBottomWidth: 1,
    borderBottomColor: '#E9F1FF',
    alignSelf: 'center',
    borderRadius: wp(3),
    marginTop: wp(5),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(2),
  },
  timeStyle: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: Colors.black,
  },
  routineTextStyle: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: Colors.mainColor,
  },
  errortxt: {
    fontSize: 10,
    color: 'red',
    fontFamily: fonts.medium,
    marginLeft: wp(3),
    marginRight: wp(5),
  },

  centerContent: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pointsBig: {
    fontSize: 30,
    fontWeight: '900',
    color: 'white', // Dark blue from your screenshot
    textAlign: 'center',
  },
  pointsSmall: {
    fontSize: 30,
    fontWeight: '700',
    color: 'white',
  },
  subtitle: {
    marginTop: 8,
    fontSize: 16,
    color: 'white',
    textAlign: 'center',
    lineHeight: 22,
  },
  myBubble: {
    backgroundColor: Colors.mainColor,
    padding: wp(3),
    borderRadius: wp(4),
    maxWidth: wp(75),
    alignSelf: 'flex-end',
  },
  userBubble: {
    backgroundColor: 'white',
    padding: wp(3),
    borderRadius: wp(4),
    maxWidth: wp(75),
    alignSelf: 'flex-start',
    elevation: 1,
  },
  messageText: {
    fontSize: wp(4),
    fontFamily: fonts.regular,
  },
  messageTime: {
    fontSize: wp(3),
    color: '#888',
    marginTop: wp(1),
  },

  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer1: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: wp(6),
    width: wp(90),
    maxHeight: hp(85),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 24,
  },
  closeButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 10,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 20,
    padding: 6,
  },
  header1: {
    marginTop: wp(2),
    marginBottom: wp(4),
  },
  title: {
    fontSize: wp(5.5),
    fontFamily: fonts.bold,
    color: Colors.black || '#1a1a1a',
    textAlign: 'center',
  },
  time: {
    fontSize: wp(3.6),
    color: '#888',
    textAlign: 'center',
    marginTop: wp(1.5),
    fontFamily: fonts.medium,
  },
  scrollContent: {
    paddingBottom: wp(4),
  },
  message: {
    fontSize: wp(4.5),
    lineHeight: wp(6.8),
    color: '#333',
    fontFamily: fonts.regular,
    marginBottom: wp(5),
  },
  image: {
    width: '100%',
    height: wp(65),
    borderRadius: 14,
    marginVertical: wp(4),
  },
  linkButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f2f2f7',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginTop: wp(4),
  },
  linkText: {
    fontSize: wp(4.4),
    color: Colors.mainColor,
    fontFamily: fonts.semiBold,
    marginRight: 8,
  },

  fullImage: {
    width: '100%',
    height: '100%',
  },
  oracleContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#00000088',
  },
  oracleImage: {
    width: '100%',
    height: '55%',
  },
  content: {
    flex: 1,
    padding: 20,
    justifyContent: 'space-between',
  },
  titlehome: {
    fontSize: 22,
    fontWeight: '600',
    textAlign: 'center',
  },
  description: {
    fontSize: 15,
    textAlign: 'center',
    color: '#555',
    marginVertical: 10,
  },
  buttonhome: {
    backgroundColor: '#2E7D32',
    paddingVertical: 14,
    borderRadius: 30,
    alignItems: 'center',
    marginBottom: 20,
  },
  buttonText: {
    color: '#FFF',
    fontSize: 16,
  },
  optionRowStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: wp(3.5),
    borderBottomWidth: 0.5,
    borderBottomColor: '#DEDEDE',
  },

  optionTextStyle: {
    fontSize: 16,
    fontFamily: fonts.medium,
    color: '#555',
    width: wp(70),
  },
  floatingButton: {
    position: 'absolute',
    bottom: 120,
    right: 30,
    backgroundColor: '#BD2BAF',
    width: 60,
    height: 60,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
